service: serverless-nodejs
app: server-app
frameworkVersion: '2'


provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  memorySize: 128
  timeout: 30

functions:
  getUsers:
    handler: handler.getUsers
    events:
      - http:
          path: users/{id}
          method: get
          cors: true
  getAllUsers:
    handler: handler.getAllUsers
    events:
      - http:
          path: users
          method: get
          cors: true
  createUsers:
    handler: handler.createUsers
    events:
      - http:
          path: users
          method: post
          cors: true
  updateUsers:
    handler: handler.updateUsers
    events:
      - http:
          path: users/{id}
          method: put
          cors: true
  deleteUsers:
    handler: handler.deleteUsers
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
  searchUsers:
    handler: handler.searchUsers
    events:
      - http:
          path: users/search
          method: post
          cors: true
plugins:
  - serverless-offline